import { z } from 'zod';

/**
 * High-level intent types for financial queries.
 */
export type QueryIntentType =
  | 'SUMMARY'   // Aggregate summary (e.g. total spent, category sum)
  | 'RANKING'   // Top merchants / categories (e.g. top spending stores)
  | 'LISTING'   // List transactions (e.g. what did I buy this week?)
  | 'COUNT'     // Transaction count query (e.g. how many times did I eat MK?)
  | 'UNKNOWN';  // Not a recognizable financial query

/**
 * Supported date range types for queries.
 */
export type DateRangeType =
  | 'TODAY'
  | 'YESTERDAY'
  | 'THIS_WEEK'
  | 'LAST_WEEK'
  | 'CURRENT_MONTH'
  | 'LAST_MONTH'
  | 'THIS_YEAR'
  | 'LAST_YEAR'
  | 'SPECIFIC_DATE'
  | 'CUSTOM_RANGE'
  | 'ALL_TIME';

export type TransactionFilterType = 'EXPENSE' | 'INCOME' | 'TRANSFER' | 'ALL';
export type GroupByType = 'CATEGORY' | 'MERCHANT' | 'DATE' | 'TYPE' | 'NONE';
export type AggregationType = 'SUM' | 'COUNT' | 'AVG' | 'NONE';
export type SortByType = 'AMOUNT' | 'DATE' | 'COUNT';
export type SortOrderType = 'ASC' | 'DESC';

/**
 * Specification for query date range.
 */
export interface DateRangeSpec {
  type: DateRangeType;
  specific_date?: string | null; // e.g. "2026-08-19"
  start_date?: string | null;    // e.g. "2026-08-01"
  end_date?: string | null;      // e.g. "2026-08-31"
}

/**
 * Resolved concrete ISO date bounds.
 */
export interface ResolvedDateRange {
  startDate: string; // YYYY-MM-DD (inclusive start)
  endDate: string;   // YYYY-MM-DD (inclusive end)
  label: string;     // Thai readable label, e.g. "เดือนนี้ (สิงหาคม 2569)"
}

/**
 * The structured Query Intent Contract.
 * Generated by the Intent Parser and consumed by the Deterministic Query Engine.
 */
export interface QueryIntent {
  intent: QueryIntentType;
  date_range: DateRangeSpec;
  transaction_type: TransactionFilterType;
  category?: string | null;
  merchant?: string | null;
  group_by?: GroupByType;
  aggregation: AggregationType;
  sort_by?: SortByType;
  sort_order?: SortOrderType;
  limit?: number;
}

/**
 * Zod schema for runtime validation of LLM parser output.
 */
export const DateRangeSpecSchema = z.object({
  type: z.enum([
    'TODAY',
    'YESTERDAY',
    'THIS_WEEK',
    'LAST_WEEK',
    'CURRENT_MONTH',
    'LAST_MONTH',
    'THIS_YEAR',
    'LAST_YEAR',
    'SPECIFIC_DATE',
    'CUSTOM_RANGE',
    'ALL_TIME',
  ]),
  specific_date: z.string().nullable().optional(),
  start_date: z.string().nullable().optional(),
  end_date: z.string().nullable().optional(),
});

export const QueryIntentSchema = z.object({
  intent: z.enum(['SUMMARY', 'RANKING', 'LISTING', 'COUNT', 'UNKNOWN']),
  date_range: DateRangeSpecSchema.default({ type: 'CURRENT_MONTH' }),
  transaction_type: z.enum(['EXPENSE', 'INCOME', 'TRANSFER', 'ALL']).default('EXPENSE'),
  category: z.string().nullable().optional(),
  merchant: z.string().nullable().optional(),
  group_by: z.enum(['CATEGORY', 'MERCHANT', 'DATE', 'TYPE', 'NONE']).nullable().optional(),
  aggregation: z.enum(['SUM', 'COUNT', 'AVG', 'NONE']).default('SUM'),
  sort_by: z.enum(['AMOUNT', 'DATE', 'COUNT', 'NONE']).nullable().optional(),
  sort_order: z.enum(['ASC', 'DESC', 'NONE']).nullable().optional(),
  limit: z.number().int().nonnegative().nullable().optional(),
});

/**
 * Itemized breakdown for categories or merchants.
 */
export interface GroupedAggregationItem {
  name: string;
  amount: number;
  count: number;
  percentage?: number;
}

/**
 * Result for a SUMMARY query.
 */
export interface SummaryQueryResult {
  type: 'SUMMARY';
  dateRange: ResolvedDateRange;
  transactionType: TransactionFilterType;
  totalAmount: number;
  transactionCount: number;
  categoryBreakdown?: GroupedAggregationItem[];
  filteredCategory?: string | null;
  filteredMerchant?: string | null;
}

/**
 * Result for a RANKING query (e.g. Top merchants or Top categories).
 */
export interface RankingQueryResult {
  type: 'RANKING';
  dateRange: ResolvedDateRange;
  transactionType: TransactionFilterType;
  groupBy: 'CATEGORY' | 'MERCHANT';
  rankings: Array<{
    rank: number;
    name: string;
    amount: number;
    count: number;
  }>;
  totalAmount: number;
}

/**
 * Result for a LISTING query.
 */
export interface ListingQueryResult {
  type: 'LISTING';
  dateRange: ResolvedDateRange;
  transactionType: TransactionFilterType;
  items: Array<{
    id: string;
    type: string;
    amount: number;
    category: string;
    merchant: string;
    description: string;
    occurredAt: string; // YYYY-MM-DD
  }>;
  totalAmount: number;
  count: number;
}

/**
 * Result for a COUNT query.
 */
export interface CountQueryResult {
  type: 'COUNT';
  dateRange: ResolvedDateRange;
  transactionType: TransactionFilterType;
  count: number;
  filteredCategory?: string | null;
  filteredMerchant?: string | null;
}

export type QueryResult =
  | SummaryQueryResult
  | RankingQueryResult
  | ListingQueryResult
  | CountQueryResult;
